# Generated by Django 3.0.2 on 2020-01-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200121_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/food/', verbose_name='Фотография блюда'),
        ),
    ]
