# Generated by Django 3.0.2 on 2020-01-22 02:37

from django.db import migrations, models
import peoplesrest.apps.store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200121_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to=peoplesrest.apps.store.models.upload_to, verbose_name='Фотография категории'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, upload_to=peoplesrest.apps.store.models.upload_to, verbose_name='Фотография блюда'),
        ),
    ]
